---
name: Documentation Improvement
description: Suggest improvements to documentation
title: "[DOCS] "
assignees: ["j4v3l"]
body:
  - type: markdown
    attributes:
      value: |
        ## Documentation Improvement

        Help us improve our documentation! Whether it's unclear instructions, missing information, or better examples.

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs improvement?
      options:
        - README.md
        - Configuration Guide (docs/CONFIGURATION.md)
        - Data Sources Guide (docs/DATA_SOURCES.md)
        - Contributing Guide (CONTRIBUTING.md)
        - Other documentation
    validations:
      required: true

  - type: textarea
    id: current-issue
    attributes:
      label: Current Issue
      description: What's wrong or missing in the current documentation?
      placeholder: "Example: The configuration section lacks a sample adsb-tui.toml"
    validations:
      required: true

  - type: textarea
    id: improvement
    attributes:
      label: Suggested Improvement
      description: How should we improve it?
      placeholder: "Example: Add a step-by-step config sample with comments"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this documentation improvement?
      options:
        - Low - Minor clarification needed
        - Medium - Important for usability
        - High - Blocks user understanding
        - Critical - Misleading or incorrect information

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any examples, screenshots, or additional context?

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have checked that this documentation issue hasn't been reported before
          required: true
