---
name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
assignees: ["j4v3l"]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request

        Thanks for suggesting a new feature! Your ideas help make ADS-B TUI better for everyone.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A brief description of the feature you'd like to see.
      placeholder: "Example: Add support for exporting flights to GeoJSON"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem/Use Case
      description: What problem would this feature solve? What's your use case?
      placeholder: "Example: Currently I must copy data manually; automation would save time"
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: "Example: Add a CLI flag `--export geojson` that writes to disk"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?
      placeholder: "I also considered..."

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important for my use case
        - Critical/blocking my usage
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Simple (small change)
        - Medium (moderate changes)
        - Complex (major changes)
        - Very Complex (architectural changes)

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any additional context, screenshots, or examples?

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please check the following.
      options:
        - label: I have searched for similar feature requests
          required: true
        - label: This feature would benefit other users, not just me
          required: true
